[build]
  command = "npm install @babel/core @babel/node @babel/preset-env && npm install --save @babel/plugin-transform-flow-strip-types && npm install @netlify/functions && npm install && npm run build"
  functions = "functions"
